name: mani_uikit
description: "Mani app UI components"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  another_flushbar: ^1.12.30
  auto_size_text: ^3.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1
  intl: any #^0.19.0
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.5.0+1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/util/gen
  integrations:
    flutter_svg: true


flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/temp/
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: fonts/Gilroy-UltraLight.ttf
          weight: 200
        - asset: fonts/Gilroy-Light.ttf
          weight: 300
        - asset: fonts/Gilroy-ExtraBold.ttf
          weight: 800
        - asset: fonts/Gilroy-Black.ttf
          weight: 900


